package org.pe.cnl.bean;

// Generated 02/12/2009 04:29:26 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ConAuditoriaAud generated by hbm2java
 */
@Entity
@Table(name = "con_auditoria_aud", catalog = "CNL_DIGEMIN")
public class ConAuditoriaAud implements java.io.Serializable {

	private Integer audNCodigo;
	private Integer audNUsuarioregistro;
	private Date audDFecharegistro;
	private String audSMetodo;
	private String audSSistemasonsulta;
	private String audSConsulta;
	private String audSCamposconsulta;

	public ConAuditoriaAud() {
	}

	public ConAuditoriaAud(Integer audNUsuarioregistro, Date audDFecharegistro,
			String audSMetodo, String audSSistemasonsulta, String audSConsulta,
			String audSCamposconsulta) {
		this.audNUsuarioregistro = audNUsuarioregistro;
		this.audDFecharegistro = audDFecharegistro;
		this.audSMetodo = audSMetodo;
		this.audSSistemasonsulta = audSSistemasonsulta;
		this.audSConsulta = audSConsulta;
		this.audSCamposconsulta = audSCamposconsulta;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "AUD_nCODIGO", unique = true, nullable = false)
	public Integer getAudNCodigo() {
		return this.audNCodigo;
	}

	public void setAudNCodigo(Integer audNCodigo) {
		this.audNCodigo = audNCodigo;
	}

	@Column(name = "AUD_nUSUARIOREGISTRO")
	public Integer getAudNUsuarioregistro() {
		return this.audNUsuarioregistro;
	}

	public void setAudNUsuarioregistro(Integer audNUsuarioregistro) {
		this.audNUsuarioregistro = audNUsuarioregistro;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "AUD_dFECHAREGISTRO", length = 0)
	public Date getAudDFecharegistro() {
		return this.audDFecharegistro;
	}

	public void setAudDFecharegistro(Date audDFecharegistro) {
		this.audDFecharegistro = audDFecharegistro;
	}

	@Column(name = "AUD_sMETODO", length = 50)
	public String getAudSMetodo() {
		return this.audSMetodo;
	}

	public void setAudSMetodo(String audSMetodo) {
		this.audSMetodo = audSMetodo;
	}

	@Column(name = "AUD_sSISTEMASONSULTA", length = 100)
	public String getAudSSistemasonsulta() {
		return this.audSSistemasonsulta;
	}

	public void setAudSSistemasonsulta(String audSSistemasonsulta) {
		this.audSSistemasonsulta = audSSistemasonsulta;
	}

	@Column(name = "AUD_sCONSULTA", length = 1000)
	public String getAudSConsulta() {
		return this.audSConsulta;
	}

	public void setAudSConsulta(String audSConsulta) {
		this.audSConsulta = audSConsulta;
	}

	@Column(name = "AUD_sCAMPOSCONSULTA", length = 100)
	public String getAudSCamposconsulta() {
		return this.audSCamposconsulta;
	}

	public void setAudSCamposconsulta(String audSCamposconsulta) {
		this.audSCamposconsulta = audSCamposconsulta;
	}

}
