package org.pe.cnl.bean;

// Generated 02/12/2009 04:29:26 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * ConPersonaPer generated by hbm2java
 */
@Entity
@Table(name = "con_persona_per", catalog = "CNL_DIGEMIN", uniqueConstraints = @UniqueConstraint(columnNames = "PER_sUSUARIO"))
public class ConPersonaPer implements java.io.Serializable {

	private Integer perNCodigo;
	private int notNCodigo;
	private int pefNCodigo;
	private String perSNombre;
	private String perSPaterno;
	private String perSMaterno;
	private Date perDNacimiento;
	private String perSNumDoc;
	private String perSUsuario;
	private String perSClave;
	private String perSEmail;
	private String perNDni;
	private Integer perFClave;
	private int colNCodigo;

	public ConPersonaPer() {
	}

	public ConPersonaPer(int notNCodigo, int pefNCodigo, String perSUsuario,
			String perSClave, int colNCodigo) {
		this.notNCodigo = notNCodigo;
		this.pefNCodigo = pefNCodigo;
		this.perSUsuario = perSUsuario;
		this.perSClave = perSClave;
		this.colNCodigo = colNCodigo;
	}

	public ConPersonaPer(int notNCodigo, int pefNCodigo, String perSNombre,
			String perSPaterno, String perSMaterno, Date perDNacimiento,
			String perSNumDoc, String perSUsuario, String perSClave,
			String perSEmail, String perNDni, Integer perFClave, int colNCodigo) {
		this.notNCodigo = notNCodigo;
		this.pefNCodigo = pefNCodigo;
		this.perSNombre = perSNombre;
		this.perSPaterno = perSPaterno;
		this.perSMaterno = perSMaterno;
		this.perDNacimiento = perDNacimiento;
		this.perSNumDoc = perSNumDoc;
		this.perSUsuario = perSUsuario;
		this.perSClave = perSClave;
		this.perSEmail = perSEmail;
		this.perNDni = perNDni;
		this.perFClave = perFClave;
		this.colNCodigo = colNCodigo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PER_nCODIGO", unique = true, nullable = false)
	public Integer getPerNCodigo() {
		return this.perNCodigo;
	}

	public void setPerNCodigo(Integer perNCodigo) {
		this.perNCodigo = perNCodigo;
	}

	@Column(name = "NOT_nCODIGO", nullable = false)
	public int getNotNCodigo() {
		return this.notNCodigo;
	}

	public void setNotNCodigo(int notNCodigo) {
		this.notNCodigo = notNCodigo;
	}

	@Column(name = "PEF_nCODIGO", nullable = false)
	public int getPefNCodigo() {
		return this.pefNCodigo;
	}

	public void setPefNCodigo(int pefNCodigo) {
		this.pefNCodigo = pefNCodigo;
	}

	@Column(name = "PER_sNOMBRE", length = 25)
	public String getPerSNombre() {
		return this.perSNombre;
	}

	public void setPerSNombre(String perSNombre) {
		this.perSNombre = perSNombre;
	}

	@Column(name = "PER_sPATERNO", length = 25)
	public String getPerSPaterno() {
		return this.perSPaterno;
	}

	public void setPerSPaterno(String perSPaterno) {
		this.perSPaterno = perSPaterno;
	}

	@Column(name = "PER_sMATERNO", length = 25)
	public String getPerSMaterno() {
		return this.perSMaterno;
	}

	public void setPerSMaterno(String perSMaterno) {
		this.perSMaterno = perSMaterno;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "PER_dNACIMIENTO", length = 0)
	public Date getPerDNacimiento() {
		return this.perDNacimiento;
	}

	public void setPerDNacimiento(Date perDNacimiento) {
		this.perDNacimiento = perDNacimiento;
	}

	@Column(name = "PER_sNUM_DOC", length = 11)
	public String getPerSNumDoc() {
		return this.perSNumDoc;
	}

	public void setPerSNumDoc(String perSNumDoc) {
		this.perSNumDoc = perSNumDoc;
	}

	@Column(name = "PER_sUSUARIO", unique = true, nullable = false, length = 50)
	public String getPerSUsuario() {
		return this.perSUsuario;
	}

	public void setPerSUsuario(String perSUsuario) {
		this.perSUsuario = perSUsuario;
	}

	@Column(name = "PER_sCLAVE", nullable = false, length = 50)
	public String getPerSClave() {
		return this.perSClave;
	}

	public void setPerSClave(String perSClave) {
		this.perSClave = perSClave;
	}

	@Column(name = "PER_sEMAIL", length = 100)
	public String getPerSEmail() {
		return this.perSEmail;
	}

	public void setPerSEmail(String perSEmail) {
		this.perSEmail = perSEmail;
	}

	@Column(name = "PER_nDNI", length = 8)
	public String getPerNDni() {
		return this.perNDni;
	}

	public void setPerNDni(String perNDni) {
		this.perNDni = perNDni;
	}

	@Column(name = "PER_fCLAVE")
	public Integer getPerFClave() {
		return this.perFClave;
	}

	public void setPerFClave(Integer perFClave) {
		this.perFClave = perFClave;
	}

	@Column(name = "COL_nCODIGO", nullable = false)
	public int getColNCodigo() {
		return this.colNCodigo;
	}

	public void setColNCodigo(int colNCodigo) {
		this.colNCodigo = colNCodigo;
	}

}
