package org.pe.cnl.bean;

// Generated 02/12/2009 04:29:26 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ConColegiosCol generated by hbm2java
 */
@Entity
@Table(name = "con_colegios_col", catalog = "CNL_DIGEMIN")
public class ConColegiosCol implements java.io.Serializable {

	private Integer colNCodigo;
	private String colSNombre;
	private String colSDireccion;

	public ConColegiosCol() {
	}

	public ConColegiosCol(String colSNombre, String colSDireccion) {
		this.colSNombre = colSNombre;
		this.colSDireccion = colSDireccion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "COL_nCODIGO", unique = true, nullable = false)
	public Integer getColNCodigo() {
		return this.colNCodigo;
	}

	public void setColNCodigo(Integer colNCodigo) {
		this.colNCodigo = colNCodigo;
	}

	@Column(name = "COL_sNOMBRE", length = 100)
	public String getColSNombre() {
		return this.colSNombre;
	}

	public void setColSNombre(String colSNombre) {
		this.colSNombre = colSNombre;
	}

	@Column(name = "COL_sDIRECCION", length = 200)
	public String getColSDireccion() {
		return this.colSDireccion;
	}

	public void setColSDireccion(String colSDireccion) {
		this.colSDireccion = colSDireccion;
	}

}
