package org.pe.cnl.bean;

// Generated 02/12/2009 04:29:26 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ConNotariaNot generated by hbm2java
 */
@Entity
@Table(name = "con_notaria_not", catalog = "CNL_DIGEMIN")
public class ConNotariaNot implements java.io.Serializable {

	private Integer notNCodigo;
	private String notSNombre;
	private String notSDireccion;
	private String notNNotario;
	private String notSTelefono;
	private String notSFax;
	private String notSEmail;
	private Integer notNUsuarios;
	private Integer colNCodigo;

	public ConNotariaNot() {
	}

	public ConNotariaNot(String notSNombre, String notSDireccion,
			String notNNotario, String notSTelefono, String notSFax,
			String notSEmail, Integer notNUsuarios, Integer colNCodigo) {
		this.notSNombre = notSNombre;
		this.notSDireccion = notSDireccion;
		this.notNNotario = notNNotario;
		this.notSTelefono = notSTelefono;
		this.notSFax = notSFax;
		this.notSEmail = notSEmail;
		this.notNUsuarios = notNUsuarios;
		this.colNCodigo = colNCodigo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "NOT_nCODIGO", unique = true, nullable = false)
	public Integer getNotNCodigo() {
		return this.notNCodigo;
	}

	public void setNotNCodigo(Integer notNCodigo) {
		this.notNCodigo = notNCodigo;
	}

	@Column(name = "NOT_sNOMBRE", length = 250)
	public String getNotSNombre() {
		return this.notSNombre;
	}

	public void setNotSNombre(String notSNombre) {
		this.notSNombre = notSNombre;
	}

	@Column(name = "NOT_sDIRECCION", length = 500)
	public String getNotSDireccion() {
		return this.notSDireccion;
	}

	public void setNotSDireccion(String notSDireccion) {
		this.notSDireccion = notSDireccion;
	}

	@Column(name = "NOT_nNOTARIO", length = 100)
	public String getNotNNotario() {
		return this.notNNotario;
	}

	public void setNotNNotario(String notNNotario) {
		this.notNNotario = notNNotario;
	}

	@Column(name = "NOT_sTELEFONO", length = 20)
	public String getNotSTelefono() {
		return this.notSTelefono;
	}

	public void setNotSTelefono(String notSTelefono) {
		this.notSTelefono = notSTelefono;
	}

	@Column(name = "NOT_sFAX", length = 20)
	public String getNotSFax() {
		return this.notSFax;
	}

	public void setNotSFax(String notSFax) {
		this.notSFax = notSFax;
	}

	@Column(name = "NOT_sEMAIL", length = 100)
	public String getNotSEmail() {
		return this.notSEmail;
	}

	public void setNotSEmail(String notSEmail) {
		this.notSEmail = notSEmail;
	}

	@Column(name = "NOT_nUSUARIOS")
	public Integer getNotNUsuarios() {
		return this.notNUsuarios;
	}

	public void setNotNUsuarios(Integer notNUsuarios) {
		this.notNUsuarios = notNUsuarios;
	}

	@Column(name = "COL_nCODIGO")
	public Integer getColNCodigo() {
		return this.colNCodigo;
	}

	public void setColNCodigo(Integer colNCodigo) {
		this.colNCodigo = colNCodigo;
	}

}
