
package gob.min.digemin.ejb;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * 172.27.0.9:8087 por 127.0.0.1
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.2-b05-RC1
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "WsDigeminService", targetNamespace = "http://ejb.digemin.min.gob/", wsdlLocation = "http://127.0.0.1:8086/digemin-digemin_ejb/EjbDigemin?wsdl")
public class WsDigeminService
    extends Service
{

    private final static URL WSDIGEMINSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(gob.min.digemin.ejb.WsDigeminService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = gob.min.digemin.ejb.WsDigeminService.class.getResource(".");
            url = new URL(baseUrl, "http://127.0.0.1:8086/digemin-digemin_ejb/EjbDigemin?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1:8086/digemin-digemin_ejb/EjbDigemin?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WSDIGEMINSERVICE_WSDL_LOCATION = url;
    }

    public WsDigeminService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsDigeminService() {
        super(WSDIGEMINSERVICE_WSDL_LOCATION, new QName("http://ejb.digemin.min.gob/", "WsDigeminService"));
    }

    /**
     * 
     * @return
     *     returns EjbDigeminWS
     */
    @WebEndpoint(name = "EjbDigeminWsPort")
    public EjbDigeminWS getEjbDigeminWsPort() {
        return super.getPort(new QName("http://ejb.digemin.min.gob/", "EjbDigeminWsPort"), EjbDigeminWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EjbDigeminWS
     */
    @WebEndpoint(name = "EjbDigeminWsPort")
    public EjbDigeminWS getEjbDigeminWsPort(WebServiceFeature... features) {
    	//return super.getPort(new QName("http://ejb.digemin.min.gob/", "EjbDigeminWsPort"), EjbDigeminWS.class, features);
        return super.getPort(new QName("http://ejb.digemin.min.gob/", "EjbDigeminWsPort"), EjbDigeminWS.class);
    }

}
